### ISSUE TITLE
Criação de modelo ER físico

### ISSUE THREAD

**Issue by L3mitch** [KauanNunesAguiar/Trabalho_final_banco_de_dados_II#1]
Responsáveis: @Yuri-Candiotto

**Comment by Yuri-Candiotto** [comment]
https://dbdiagram.io/d/655feb373be1495787a0d9f7
[Modelo Físico - PDF.pdf](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/files/13462385/Modelo.Fisico.-.PDF.pdf)

**Comment by L3mitch** [comment]
Adicionar informação "Nível de Acesso" para a tabela Usuario

**Comment by L3mitch** [comment]
Atualizar modelo físico com base nas alterações feita no script de DDL.

**Comment by Yuri-Candiotto** [comment]
https://dbdiagram.io/d/656e62bf56d8064ca0604658
Modelo físico atualizado  conforme as alterações feitas no script DDL
