### ISSUE TITLE
Dicionário de dados

### ISSUE THREAD

**Issue by L3mitch** [KauanNunesAguiar/Trabalho_final_banco_de_dados_II#3]
Responsável: @suyane924

**Comment by suyane924** [comment]
[Dicionario-de-Dados.xlsx](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/files/13532545/Dicionario-de-Dados.xlsx)

**Comment by suyane924** [comment]
Dicionário de dados atualizado conforme as alterações feitas no DDL.  Falta apenas preenchê-lo na parte dos índices, depois que eles forem criados.

[Dicionario-de-Dados (2) (1).xlsx](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/files/13619138/Dicionario-de-Dados.2.1.xlsx)

**Comment by L3mitch** [comment]
Pequenas alterações feitas

[Dicionario-de-Dados.xlsx](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/files/13620984/Dicionario-de-Dados.xlsx)
