### ISSUE TITLE
Geração de scripts DDL

### ISSUE THREAD

**Issue by L3mitch** [KauanNunesAguiar/Trabalho_final_banco_de_dados_II#4]
Responsável: @Yuri-Candiotto

**Comment by Yuri-Candiotto** [comment]
[código - create table.pdf](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/files/13462406/codigo.-.create.table.pdf)

**Comment by L3mitch** [comment]
Alterei algumas coisas no código, adicionei a coluna de nível de acesso de usuário, alterei o valor dos VARCHARs da coluna 'telefone' e foi adicionado o IDENTITY nas colunas de ID para acréscimo automático de ID conforme novos usuários são inseridos no banco

**Comment by L3mitch** [comment]
## Alterações:
### Tipo da variável da coluna 'Duracao' se tornou TIME
### Método de pagamento agora é um CHAR(1) que verifica se o valor inserido é 'C', 'D', 'E' ou 'P':
+ C = Crédito
+ D = Débito
+ E = Espécie
+ P = Pix

[Link de acesso ao arquivo DDL](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/blob/main/scripts_sql/scripts_ddl.sql)
