### ISSUE TITLE
Geração de scripts de criação de massa de dados

### ISSUE THREAD

**Issue by L3mitch** [KauanNunesAguiar/Trabalho_final_banco_de_dados_II#5]
Responsável: Elias Enns

**Comment by EliasEnns** [comment]
[Script de criação de massa de dados](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/files/13540544/DADOS.txt)

**Comment by L3mitch** [comment]
#### Alterações:
Fiz umas pequenas alterações removendo o insert de colunas que já possuem identity
Alterei a formato das datas que estavam em 'AAAA-MM-DD' para 'DD-MM-AAAA' pois o SQL Server está com a região setada para Brasil.

[Link de acesso ao arquivo DML](https://github.com/KauanNunesAguiar/Trabalho_final_banco_de_dados_II/blob/main/scripts_sql/scripts_dml.sql)
