### ISSUE TITLE
Desenvolvimento do projeto no Github

### ISSUE THREAD

**Issue by jlsilva01** [KauanNunesAguiar/Trabalho_final_banco_de_dados_II#8]
Pessoal, o projeto de vocês segue com muito poucaa atualização no GitHub,
Utilizem este repositorio como modelo - https://github.com/jlsilva01/projeto_final_bd2_satc_2023 - um podem fazer um fork do repo e atualizar com as informacoes de vocês.

Importante também dar visibilidade das atividades que estao sendo realizadas pelo grupo atraves de issues. Vejo que algumas issues foram criadas, mas com muito pouca atualizacao nelas.

Lembrando que toda a dinamica do Github também faz parte do desenvolvimento do trabalho.

Hoje no checkpoint de logo mais a noite reforço este ponto com voces e esclareco algumas duvidas que por ventura tenha ficado.

**Comment by L3mitch** [comment]
O Github foi remodelado com base no exemplo
